
mainWeb = "https://www.mtggoldfish.com/"
webModern = "https://www.mtggoldfish.com/metagame/modern/full#paper"
webPioneer = "https://www.mtggoldfish.com/metagame/pioneer/full#paper"
webStandard = "https://www.mtggoldfish.com/metagame/standard/full#paper"
tmp = "./tmp/"
tmpModern = "./tmp/modern.txt"
tmpPioneer = "./tmp/pioneer.txt"
tmpStandard = "./tmp/standard.txt"
deck = "./decks/"
