# Generated by Django 3.0.4 on 2020-09-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sets',
            name='id',
        ),
        migrations.AlterField(
            model_name='sets',
            name='code',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
