# Generated by Django 3.0.4 on 2020-09-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0002_auto_20200921_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deckcards',
            fields=[
                ('id_deckcard', models.AutoField(primary_key=True, serialize=False)),
                ('card_name', models.TextField(blank=True, null=True)),
                ('cant', models.IntegerField(blank=True, null=True)),
                ('side', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deckcards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Decks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('format', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'decks',
                'managed': False,
            },
        ),
    ]
